# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nspanach <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/09 14:33:56 by nspanach          #+#    #+#              #
#    Updated: 2018/08/09 14:34:13 by nspanach         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_cat
SRCS=srcs/*.c

all:
	 gcc $(SRCS) -o $(NAME)

clean:
	 /bin/rm -f *.o

fclean: clean
	 /bin/rm -f $(NAME)

re: fclean re
